name: Zip and Commit Minecraft Resource Pack

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'SquidTweaks.zip'        # Avoid infinite loops
      - 'SquidTweaks.zip.sha1'   # Don't trigger on hash file

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for pushing

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Zip the resource pack folder
        run: |
          cd SquidTweaks
          zip -r ../SquidTweaks.zip .

      - name: Compute SHA1 and write to file
        run: |
          sha1sum SquidTweaks.zip | cut -d ' ' -f 1 > SquidTweaks.zip.sha1
          echo "SHA1 = $(cat SquidTweaks.zip.sha1)"

      - name: Zip the resource pack folder
        run: |
          cd SquidTweaksSuper
          zip -r ../SquidTweaksSuper.zip .

      - name: Compute SHA1 and write to file
        run: |
          sha1sum SquidTweaksSuper.zip | cut -d ' ' -f 1 > SquidTweaksSuper.zip.sha1
          echo "SHA1 = $(cat SquidTweaksSuper.zip.sha1)"

      - name: Commit and push the zip + sha1
        run: |
          git add SquidTweaks.zip SquidTweaks.zip.sha1 SquidTweaksSuper.zip SquidTweaksSuper.zip.sha1
          git diff --cached --quiet || git commit -m "Auto-update zipped packs and SHA1"
          git push
